#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build en/index.html from index.html using translate_map.py.

Walks the DOM (not regex on raw HTML) so translation only touches actual
text content and the `alt` attribute — markup, classes, inline SVG
structure, embedded images, and the timeline SVG's shapes are untouched.

Re-run this any time index.html changes and translate_map.py has been
updated to cover the new/changed text (see translate_map.py's coverage
check for how to find what's missing).
"""
import os
import re
import sys
from bs4 import BeautifulSoup, Comment

HERE = os.path.dirname(os.path.abspath(__file__))

from translate_map import TRANSLATIONS, ALT_TRANSLATIONS

SRC = "index.html"
DST = "en/index.html"

JP_RE = re.compile(r'[぀-ヿ一-鿿]')


def translate_text_nodes(soup):
    missing = []
    for el in soup.find_all(string=True):
        if el.parent.name in ("script", "style"):
            continue
        if isinstance(el, Comment):
            continue
        raw = str(el)
        if not JP_RE.search(raw):
            continue
        stripped = raw.strip()
        if stripped in TRANSLATIONS:
            # preserve any leading/trailing whitespace the original node had
            leading = raw[:len(raw) - len(raw.lstrip())]
            trailing = raw[len(raw.rstrip()):]
            el.replace_with(leading + TRANSLATIONS[stripped] + trailing)
        else:
            missing.append(stripped)
    return missing


def translate_attrs(soup):
    missing = []
    for tag in soup.find_all(attrs={"alt": True}):
        a = tag.get("alt", "")
        if not JP_RE.search(a):
            continue
        if a in ALT_TRANSLATIONS:
            tag["alt"] = ALT_TRANSLATIONS[a]
        else:
            missing.append(a)

    for tag in soup.find_all(attrs={"aria-label": True}):
        v = tag.get("aria-label", "")
        if not JP_RE.search(v):
            continue
        if v in TRANSLATIONS:
            tag["aria-label"] = TRANSLATIONS[v]
        else:
            missing.append(v)

    for tag in soup.find_all("meta"):
        v = tag.get("content", "")
        if not JP_RE.search(v):
            continue
        if v in TRANSLATIONS:
            tag["content"] = TRANSLATIONS[v]
        else:
            missing.append(v)

    return missing


def main():
    html = open(SRC, encoding="utf-8").read()
    soup = BeautifulSoup(html, "html.parser")

    missing_text = translate_text_nodes(soup)
    missing_attr = translate_attrs(soup)

    if missing_text or missing_attr:
        print("ERROR: missing translations, aborting:", file=sys.stderr)
        for m in missing_text:
            print("  text:", repr(m), file=sys.stderr)
        for m in missing_attr:
            print("  alt:", repr(m), file=sys.stderr)
        sys.exit(1)

    # lang attribute + hreflang alternates for the two versions
    html_tag = soup.find("html")
    if html_tag:
        html_tag["lang"] = "en"

    # Swap in the properly-rendered English timeline SVG (word-wrapped,
    # generated by profile-updater/gen_timeline.py) instead of the one the
    # generic text-node translation above just produced — English text is
    # longer than Japanese per line and needs the wrap-aware renderer, not
    # a 1:1 string substitution into the Japanese layout.
    en_svg_path = os.path.join(HERE, "..", "profile-updater", "output", "timeline_en_dark.svg")
    if os.path.exists(en_svg_path):
        new_svg = open(en_svg_path, encoding="utf-8").read().strip()
        new_svg = new_svg.replace("<svg viewBox=", '<svg class="timeline-svg" viewBox=', 1)
        current = str(soup)
        m = re.search(r'<svg class="timeline-svg".*?</svg>', current, re.S)
        if m:
            soup = BeautifulSoup(current[:m.start()] + new_svg + current[m.end():], "html.parser")
        else:
            print("WARNING: could not find timeline svg placeholder to replace", file=sys.stderr)
    else:
        print(f"WARNING: {en_svg_path} not found — run profile-updater/gen_timeline.py first. "
              "English page will have the generic (non-wrapped) timeline SVG.", file=sys.stderr)

    # the language-switcher <select> is identical markup on both pages
    # except which <option> is selected — flip it here rather than via
    # the generic text-translation path.
    switcher = soup.find("select", attrs={"class": "lang-switch"})
    if switcher is None:
        print("WARNING: lang-switch <select> not found — skipping", file=sys.stderr)
    else:
        for opt in switcher.find_all("option"):
            if opt.get("value") == "en":
                opt["selected"] = ""
            elif "selected" in opt.attrs:
                del opt["selected"]

    out = str(soup)
    with open(DST, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"wrote {DST} ({len(out)} bytes)")


if __name__ == "__main__":
    main()
